on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main

name: Continuous integration

env:
  BASE_IMAGE_NAME: xvandish-livegrep/base
  INDEXER_IMAGE_NAME: xvandish-livegrep/indexer
  NGINX_IMAGE_NAME: xvandish-livegrep/nginx

# https://github.com/actions/runner/issues/1039 - GITHUB_TOKEN works only for the main branch
# so it won't work for the pull_requests. Just use a PAT then 
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{runner.os}}-${{hashFiles('WORKSPACE')}}
          restore-keys: |
            ${{runner.os}}-
      - name: setup bazel
        run: |
          cat .bazelrc.ci >> .bazelrc
      - name: bazel fetch
        run: |
          bazel fetch //cmd/...
      - name: gofmt
        run: |
          gofmt=$(bazel info output_base)/external/go_sdk/bin/gofmt
          format_errors=$(find . -name '*.go' -print0 | xargs -0 "$gofmt" -l -e)
          if [ "$format_errors" ]; then
              echo "=== misformatted files (run gofmt) ==="
              echo "$format_errors"
              exit 1
          fi
      - name: bazel test, build
        run: |
          bazel test --test_arg=-test.v //...
          bazel build //...
          echo "build_output_file_name=$(./package.sh)" >> $GITHUB_ENV
      - name: upload build output
        uses: actions/upload-artifact@v2
        with: 
          name: "${{ env.build_output_file_name }}"
          path: "builds/${{ env.build_output_file_name }}.tgz"
      - name: Build images
        run: |
          # the first image is tagged because subsequent images build from it
          docker build -t $BASE_IMAGE_NAME --file docker/base/Dockerfile --build-arg "livegrep_version=$build_output_file_name"  .
          docker build -t $INDEXER_IMAGE_NAME . --file docker/indexer/Dockerfile
          docker build -t $NGINX_IMAGE_NAME . --file docker/nginx/Dockerfile
      - name: Push images
        run: |
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          BASE_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$BASE_IMAGE_NAME
          INDEXER_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$INDEXER_IMAGE_NAME
          NGINX_IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$NGINX_IMAGE_NAME

          # same version as made by package.sh
          VERSION=$(git rev-parse HEAD | head -c10)

          [ "${{ github.ref }}" == "main" ] && VERSION=latest

          echo VERSION=$VERSION

          docker tag $BASE_IMAGE_NAME $BASE_IMAGE_ID:$VERSION
          docker tag $INDEXER_IMAGE_NAME $INDEXER_IMAGE_ID:$VERSION
          docker tag $NGINX_IMAGE_NAME $NGINX_IMAGE_ID:$VERSION

          docker push $NGINX_IMAGE_ID:$VERSION
          docker push $BASE_IMAGE_ID:$VERSION
          docker push $INDEXER_IMAGE_ID:$VERSION
          
