on:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run in cron every night to keep the cache warm.
    # Github prunes caches every 7 days, and I don't push often
    # enough to keep our cache from being evicted without this.
    - cron: '7 6 * * *'

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/bazel
          key: ${{runner.os}}-${{hashFiles('WORKSPACE')}}
          restore-keys: |
            ${{runner.os}}-
      - name: setup bazel
        run: |
          cat .bazelrc.ci >> .bazelrc
      - name: bazel fetch
        run: |
          bazel fetch //cmd/...
      - name: gofmt
        run: |
          gofmt=$(bazel info output_base)/external/go_sdk/bin/gofmt
          format_errors=$(find . -name '*.go' -print0 | xargs -0 "$gofmt" -l -e)
          if [ "$format_errors" ]; then
              echo "=== misformatted files (run gofmt) ==="
              echo "$format_errors"
              exit 1
          fi
      - name: bazel test, build
        run: |
          bazel test --test_arg=-test.v //...
          bazel build //...
          echo "build_output_file_name=$(./package.sh)" >> $GITHUB_ENV
      - name: upload build output
        uses: actions/upload-artifact@v2
        with: 
          name: "${{ env.build_output_file_name }}"
          path: "builds/${{ env.build_output_file_name }}.tgz"
